// <auto-generated />
using CaixaEletronico.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaixaEletronico.Infra.Migrations
{
    [DbContext(typeof(CaixaEletronicoContext))]
    [Migration("20241222175830_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CaixaEletronico.Domain.Entities.ValorMonetario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ValoresMonetarios", (string)null);
                });

            modelBuilder.Entity("CaixaEletronico.Domain.Entities.ValorMonetario", b =>
                {
                    b.OwnsOne("CaixaEletronico.Domain.ValueObjects.Quantidade", "Quantidade", b1 =>
                        {
                            b1.Property<int>("ValorMonetarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Amount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quantidade");

                            b1.HasKey("ValorMonetarioId");

                            b1.ToTable("ValoresMonetarios");

                            b1.WithOwner()
                                .HasForeignKey("ValorMonetarioId");
                        });

                    b.OwnsOne("CaixaEletronico.Domain.ValueObjects.TipoMoeda", "TipoMoeda", b1 =>
                        {
                            b1.Property<int>("ValorMonetarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("TipoMoeda");

                            b1.HasKey("ValorMonetarioId");

                            b1.ToTable("ValoresMonetarios");

                            b1.WithOwner()
                                .HasForeignKey("ValorMonetarioId");
                        });

                    b.OwnsOne("CaixaEletronico.Domain.ValueObjects.Valor", "valor", b1 =>
                        {
                            b1.Property<int>("ValorMonetarioId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("ValorMonetarioId");

                            b1.ToTable("ValoresMonetarios");

                            b1.WithOwner()
                                .HasForeignKey("ValorMonetarioId");
                        });

                    b.Navigation("Quantidade")
                        .IsRequired();

                    b.Navigation("TipoMoeda")
                        .IsRequired();

                    b.Navigation("valor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
